import type { ResumeData } from '../../shared/resume'

/** Full four-page review fixture reproduced from naledi-mkhize-resume.pdf. */
export const nalediMkhizeResume: ResumeData = {
  personalDetails: {
    firstName: 'Naledi',
    lastName: 'Mkhize',
    professionalTitle: 'Senior Front-End Developer and Digital Solutions Specialist',
    email: 'naledi.mkhize@example.com',
    phone: '+27 82 555 0198',
    city: 'Durban, KwaZulu-Natal',
    country: 'South Africa',
    linkedInUrl: 'https://www.linkedin.com/in/naledi-mkhize',
    portfolioUrl: 'https://naledi-mkhize.example.com',
  },
  photograph: null,
  professionalOverview:
    'Results-driven Senior Front-End Developer and Digital Solutions Specialist with more than eight years of experience designing, developing and maintaining responsive websites, e-commerce platforms and business applications. Experienced in React, TypeScript, JavaScript, Shopify, accessibility, performance optimisation and API integration. Skilled at translating complex business requirements and design systems into reliable, user-friendly digital experiences. Comfortable collaborating with international clients, designers, developers, quality-assurance teams and project managers. Known for careful attention to detail and dependable delivery.',
  strengths: [
    'Translating complex requirements into practical technical solutions',
    'Building accessible and responsive interfaces',
    'Diagnosing difficult front-end and integration problems',
    'Communicating clearly with technical and non-technical stakeholders',
    'Managing several projects and deadlines simultaneously',
    'Maintaining high standards of quality and attention to detail',
    'Learning new technologies and platforms quickly',
    'Working independently in remote and international teams',
  ],
  employmentHistory: [
    {
      jobTitle: 'Senior Front-End Developer',
      employer: 'BrightWave Digital Solutions',
      employmentType: 'Full-time',
      city: 'Durban',
      country: 'South Africa',
      startDate: { month: 1, year: 2023 },
      endDate: null,
      currentlyWorkingHere: true,
      description:
        'Lead the front-end development of websites, customer portals and internal business tools for local and international clients. Convert Figma designs and business requirements into responsive React and TypeScript components while maintaining accessibility, browser compatibility and performance standards. Collaborate with designers, backend developers, quality-assurance analysts and project managers throughout planning, implementation, testing and release.',
      achievements: [
        'Created a reusable component library that reduced duplicated development work across projects.',
        'Improved page-loading performance through image optimisation, lazy loading and JavaScript bundle reduction.',
        'Introduced accessibility reviews that improved keyboard navigation and screen-reader compatibility.',
        'Mentored junior developers through code reviews, documentation and technical workshops.',
        'Delivered multiple time-sensitive product launches without critical production defects.',
      ].join('\n'),
    },
    {
      jobTitle: 'Shopify and E-commerce Developer',
      employer: 'CommerceCraft Africa',
      employmentType: 'Full-time',
      city: 'Cape Town',
      country: 'South Africa',
      startDate: { month: 3, year: 2020 },
      endDate: { month: 12, year: 2022 },
      currentlyWorkingHere: false,
      description:
        'Developed and maintained Shopify stores for fashion, beauty, homeware and professional-service brands. Created custom Liquid sections, product templates, promotional landing pages and theme settings. Integrated payment, shipping, analytics and marketing applications while ensuring that stores remained responsive, secure and easy for clients to manage.',
      achievements: [
        'Rebuilt several outdated storefronts using responsive, conversion-focused layouts.',
        'Improved checkout journeys by simplifying navigation and strengthening calls to action.',
        'Diagnosed theme, application and tracking conflicts affecting customer purchases.',
        'Created documentation that allowed clients to update products and promotions independently.',
        'Supported major seasonal campaigns with rapid testing and production fixes.',
      ].join('\n'),
    },
    {
      jobTitle: 'Front-End Web Developer',
      employer: 'Horizon Creative Agency',
      employmentType: 'Full-time',
      city: 'Johannesburg',
      country: 'South Africa',
      startDate: { month: 6, year: 2018 },
      endDate: { month: 2, year: 2020 },
      currentlyWorkingHere: false,
      description:
        'Built responsive marketing websites and landing pages using HTML, CSS, Sass, JavaScript and content-management systems. Worked closely with UX designers to reproduce approved layouts accurately across desktop, tablet and mobile screens. Maintained existing client websites, corrected browser inconsistencies and implemented content and campaign updates.',
      achievements: [
        'Delivered more than 25 responsive websites and campaign pages.',
        'Created reusable layout patterns that shortened delivery times for recurring campaigns.',
        'Reduced cross-browser defects by introducing structured browser-testing checklists.',
        'Improved website accessibility through semantic HTML and consistent form labelling.',
        'Received positive client feedback for reliability and accurate design implementation.',
      ].join('\n'),
    },
    {
      jobTitle: 'Quality Assurance Analyst',
      employer: 'NextStep Software Services',
      employmentType: 'Full-time',
      city: 'Durban',
      country: 'South Africa',
      startDate: { month: 2, year: 2016 },
      endDate: { month: 5, year: 2018 },
      currentlyWorkingHere: false,
      description:
        'Performed functional, regression, usability and cross-browser testing for websites and internal software applications. Reviewed requirements, prepared test cases, documented defects and worked with developers to confirm fixes. Participated in release planning and helped ensure that production deployments met the agreed acceptance criteria.',
      achievements: [
        'Developed reusable regression-test suites for the organisation’s main products.',
        'Improved defect reports by including clear reproduction steps, evidence and severity ratings.',
        'Identified high-impact usability problems before several major product releases.',
        'Helped standardise browser and mobile-device testing across the team.',
        'Supported user-acceptance testing with clients and internal stakeholders.',
      ].join('\n'),
    },
    {
      jobTitle: 'Junior Web Developer',
      employer: 'Coastal Media Studio',
      employmentType: 'Full-time',
      city: 'Umhlanga',
      country: 'South Africa',
      startDate: { month: 1, year: 2014 },
      endDate: { month: 1, year: 2016 },
      currentlyWorkingHere: false,
      description:
        'Assisted with the development and maintenance of small-business websites, newsletters and promotional landing pages. Updated content, corrected styling problems, prepared image assets and tested pages across common browsers and screen sizes. Worked with senior developers to learn development standards, version control and production-release procedures.',
      achievements: [
        'Built responsive pages from supplied visual designs.',
        'Corrected legacy CSS issues affecting mobile layouts.',
        'Prepared reusable email and landing-page templates.',
        'Maintained accurate records of website changes and client requests.',
        'Progressed from content updates to independent front-end development tasks.',
      ].join('\n'),
    },
  ],
  education: [
    {
      qualification: 'Bachelor of Science in Information Technology',
      institution: 'University of South Africa',
      city: 'South Africa',
      country: 'South Africa',
      startDate: { month: 1, year: 2015 },
      endDate: { month: 1, year: 2018 },
      currentlyStudying: false,
      description:
        'Focused on software development, databases, systems analysis, web technologies, human-computer interaction and information-security fundamentals. Completed practical assignments involving application design, programming, testing and technical documentation.',
    },
    {
      qualification: 'National Diploma in Information Technology',
      institution: 'Durban University of Technology',
      city: 'Durban',
      country: 'South Africa',
      startDate: { month: 1, year: 2011 },
      endDate: { month: 12, year: 2013 },
      currentlyStudying: false,
      description:
        'Studied programming, web development, database design, networking, business analysis and software-testing principles. Completed a final project involving the design and development of a responsive business-management application.',
    },
    {
      qualification: 'National Senior Certificate',
      institution: 'Durban Central Secondary School',
      city: 'Durban',
      country: 'South Africa',
      startDate: { month: 1, year: 2006 },
      endDate: { month: 12, year: 2010 },
      currentlyStudying: false,
      description:
        'Completed secondary education with subjects including Mathematics, English, Information Technology, Business Studies and Physical Sciences.',
    },
  ],
  technicalSkills: [
    'React',
    'TypeScript',
    'JavaScript',
    'HTML5',
    'CSS3',
    'Sass',
    'Shopify Liquid',
    'Git and GitHub',
    'Vite',
    'REST API integration',
    'Responsive web development',
    'Web accessibility',
    'Performance optimisation',
    'Figma implementation',
    'Vitest and component testing',
  ],
  softSkills: [
    'Problem-solving',
    'Written communication',
    'Verbal communication',
    'Attention to detail',
    'Time management',
    'Adaptability',
    'Team collaboration',
    'Critical thinking',
    'Client communication',
    'Independent remote working',
  ],
  trainingAndCertificates: [
    ['Advanced React and TypeScript', 'Udemy', 1, 2026],
    ['Shopify Theme Development', 'Shopify Academy', 1, 2025],
    ['Web Accessibility Fundamentals', 'W3C', 1, 2025],
    ['JavaScript Algorithms and Data Structures', 'freeCodeCamp', 1, 2024],
    ['Google Analytics Certification', 'Google', 1, 2024],
    ['Git and GitHub Professional Workflow', 'LinkedIn Learning', 1, 2023],
    ['Agile Project Management Fundamentals', 'Alison', 1, 2023],
    ['Software Testing Fundamentals', 'ISTQB Training Provider', 1, 2022],
    ['Responsive Web Design', 'freeCodeCamp', 1, 2021],
    ['UX Design Foundations', 'Interaction Design Foundation', 1, 2020],
  ].map(([name, issuingOrganisation, month, year]) => ({
    name: String(name),
    issuingOrganisation: String(issuingOrganisation),
    completionDate: { month: Number(month), year: Number(year) },
    inProgress: false,
    credentialId: '',
    credentialUrl: '',
  })),
  languages: [
    { name: 'English', proficiency: 'Fluent' },
    { name: 'isiZulu', proficiency: 'Native' },
    { name: 'Afrikaans', proficiency: 'Conversational' },
    { name: 'French', proficiency: 'Basic' },
  ],
  interests: [
    'Emerging web technologies and artificial intelligence',
    'Mentoring junior developers',
    'Digital accessibility and inclusive design',
    'Community technology workshops',
    'User-experience research',
    'Photography and visual design',
    'Reading about entrepreneurship and product development',
    'Hiking and nature conservation',
  ],
}
